name: Force Sync Branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  force-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Commit all changes and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Christbowel"
          git config user.email "96427513+Christbowel@users.noreply.github.com"
          
          git fetch origin main
          git checkout main
          
          echo "$(date)" > .github/sync_trigger.txt
          
          git add -A
          
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: docs update and force sync repository baseline"
            
            # 5. On pousse proprement. Si le serveur a avancé entre-temps, on rebase automatiquement
            git push origin main
          else
            echo "Aucune modification à commit."
          fi
